on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '20 16 * * 1-5'

jobs:
  check_salaries:
    name: Check salaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Salaries
        run: ./salaries.rb -a >> $GITHUB_STEP_SUMMARY

