on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '20 16 * * 1-5'

jobs:
  check_salaries:
    name: Check salaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Salaries
        run: |
          ./salaries.rb -cEUR -fmarkdown >> $GITHUB_STEP_SUMMARY
          ./salaries.rb -cUSD -fmarkdown >> $GITHUB_STEP_SUMMARY

